
import java.lang.reflect.Array;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        this.setLocationRelativeTo(null); // Used to centre the register frame
        
        
    }
    
    loginUser lg = new loginUser(); 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Register_Label = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        password_Label = new javax.swing.JLabel();
        username_Label = new javax.swing.JLabel();
        Rusername_textfield = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        returnToLoginButton = new javax.swing.JButton();
        firstnameLabel = new javax.swing.JLabel();
        firstname_textfield = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastname_textfield = new javax.swing.JTextField();
        newpassword_Label = new javax.swing.JLabel();
        password_textfield = new javax.swing.JPasswordField();
        password_textfield2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        Register_Label.setBackground(new java.awt.Color(255, 255, 255));
        Register_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Register_Label.setForeground(new java.awt.Color(255, 255, 255));
        Register_Label.setText("Register");

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        minimizeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        minimizeLabel.setText("-");
        minimizeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        password_Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_Label.setForeground(new java.awt.Color(255, 255, 255));
        password_Label.setText("Password");

        username_Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username_Label.setForeground(new java.awt.Color(255, 255, 255));
        username_Label.setText("Username");

        Rusername_textfield.setBackground(new java.awt.Color(102, 102, 102));
        Rusername_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Rusername_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rusername_textfieldActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(0, 0, 153));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonRegister.setBackground(new java.awt.Color(255, 102, 0));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        returnToLoginButton.setBackground(new java.awt.Color(255, 255, 0));
        returnToLoginButton.setText("Click here to login to account");
        returnToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnToLoginButtonMouseClicked(evt);
            }
        });
        returnToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToLoginButtonActionPerformed(evt);
            }
        });

        firstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setText("First Name");

        firstname_textfield.setBackground(new java.awt.Color(102, 102, 102));
        firstname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_textfieldActionPerformed(evt);
            }
        });

        lastnameLabel.setBackground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setText("Last Name");

        lastname_textfield.setBackground(new java.awt.Color(102, 102, 102));
        lastname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastname_textfieldActionPerformed(evt);
            }
        });

        newpassword_Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newpassword_Label.setForeground(new java.awt.Color(255, 255, 255));
        newpassword_Label.setText("Re-Enter Password:");

        password_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textfieldActionPerformed(evt);
            }
        });

        password_textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textfield2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rusername_textfield)
                    .addComponent(returnToLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegister))
                    .addComponent(firstnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstname_textfield)
                    .addComponent(lastnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastname_textfield)
                    .addComponent(newpassword_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password_textfield)
                    .addComponent(password_textfield2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rusername_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newpassword_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(returnToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Register_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register_Label)
                    .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0); // Allows Register frame to be terminated
    }//GEN-LAST:event_exitLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED); // Minimizes Register frame
        
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void Rusername_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rusername_textfieldActionPerformed
        // TODO add your handling code here:
        String fn ;// Variable for username
         
        
        fn = Rusername_textfield.getText(); // Gets username input
        System.out.println(fn); // To check if method is working
        
    }//GEN-LAST:event_Rusername_textfieldActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        
        
       
        boolean checkUsername; // Boolean variable
        boolean checkPassword; // Boolean variable
        //( Farrell , 2019)
        String fn;// Variable for Firstname
        fn = firstname_textfield.getText();// Gets Firstname input
        System.out.println(fn);// To check if method is working
        
        String ln;// Variable for Lastname 
        ln = lastname_textfield.getText();
        System.out.println(ln);// To check if method is working
        
        
        String ru; // variable for username
        ru = Rusername_textfield.getText(); // Gets username input
        System.out.println(ru);// To check if the method is working
        
        
        checkUsername = lg.checkUserName(ru); // Compares 
        String ptf;// Variable for password
        ptf = password_textfield.getText(); // Gets password input
        System.out.println(ptf);// To check if the method is working
        
        
        
        String ptf2;// String for confirmation password
        ptf2 = password_textfield2.getText();// Gets confirmation password input
        System.out.println(ptf2);// To check if the method is working
        
        
        checkPassword = lg.checkPasswordComplexity(ptf2); // Compares password in register frame and in JOption interface
        
        lg.registerUser(checkPassword, checkUsername , ru , ptf2 , fn , ln); // instantiates an object with a registerUser method call
        
        
        if (checkPassword && checkUsername){ // Condition for if username and Password are the same in Register frame and JOption interface 
            lg.setFname(fn);
            lg.setSname(ln);
            lg.setUname(ru); 
            lg.setUpass(ptf2);
        }
        
    
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void returnToLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnToLoginButtonMouseClicked
       
        
    }//GEN-LAST:event_returnToLoginButtonMouseClicked

    private void returnToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToLoginButtonActionPerformed
        
        String tempuser = JOptionPane.showInputDialog(null , " Enter Username: ");
        String temppass = JOptionPane.showInputDialog(null , " Enter Password: ");
        lg.loginUser(tempuser,temppass); // Temporary variables are passed into the loginUser method where the username and password will be stored
        Arrayuser newuser1 = new Arrayuser();// call of array class
        newuser1.array1();  // array class being instantiated by array1 method
        Taskuser newtsk = new Taskuser();//call of Task class
       
        
        
        // ( Farrell , 2019)
    }//GEN-LAST:event_returnToLoginButtonActionPerformed

    private void firstname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_textfieldActionPerformed
        // TODO add your handling code here:
        firstnameLabel.getText(); // Gets user First name
    }//GEN-LAST:event_firstname_textfieldActionPerformed

    private void lastname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastname_textfieldActionPerformed
        // TODO add your handling code here:
         lastnameLabel.getText(); // Gets user Last name
    }//GEN-LAST:event_lastname_textfieldActionPerformed

    private void password_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textfieldActionPerformed
        // TODO add your handling code here:
        password_textfield.getText(); // Gets user password input
    }//GEN-LAST:event_password_textfieldActionPerformed

    private void password_textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textfield2ActionPerformed
        // TODO add your handling code here:
        password_textfield.getText();// Gets user second confirmation password 
    }//GEN-LAST:event_password_textfield2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Register_Label;
    private javax.swing.JTextField Rusername_textfield;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstname_textfield;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastname_textfield;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel newpassword_Label;
    private javax.swing.JLabel password_Label;
    private javax.swing.JPasswordField password_textfield;
    private javax.swing.JPasswordField password_textfield2;
    private javax.swing.JButton returnToLoginButton;
    private javax.swing.JLabel username_Label;
    // End of variables declaration//GEN-END:variables

   
      

  
   
    }

/**
Reference List
© 2019 Cengage Learning Inc. Java Programming Ninth Edition by Joyce Farrell
Analyzing a Java Application that Produces Console Output Page 12 Chapter 1
Using Input Dialog Boxes Page 82 Chapter 2
// See Seven minute Methods - Boolean Methods - Paul Miskew 2013 added by Paul Miskew available at https://youtu.be/aMseR3t7Jbk
[Accessed 8 May 2022]
See fourty four minute video Java  How to Design Login And Register Form In Java Netbeans - 1BestCsharp blog added by 1BestCsharp available at https://youtu.be/XAowXcmQ-kA
[Accessed 5 May 2022]
 */